apiVersion: 1

datasources:
  - name: Prometheus Live Demo
    type: prometheus
    uid: anomaly-demo-prometheus
    access: proxy
    url: http://host.docker.internal:9091
    isDefault: false
    editable: false
    jsonData:
      httpMethod: POST
      timeInterval: 5s
