services:
  grafana:
    user: root
    container_name: 'alpas-anomalydetector-panel'

    build:
      context: .
      args:
        grafana_image: ${GRAFANA_IMAGE:-grafana-enterprise}
        grafana_version: ${GRAFANA_VERSION:-12.4.0}
        development: ${DEVELOPMENT:-false}
        anonymous_auth_enabled: ${ANONYMOUS_AUTH_ENABLED:-true}
    ports:
      - ${GRAFANA_PORT:-3000}:3000/tcp
    volumes:
      - ../dist:/var/lib/grafana/plugins/alpas-anomalydetector-panel
      - ../provisioning:/etc/grafana/provisioning
      - ..:/root/alpas-anomalydetector-panel
    extra_hosts:
      - 'host.docker.internal:host-gateway'

    environment:
      NODE_ENV: development
      GF_LOG_FILTERS: plugin.alpas-anomalydetector-panel:debug
      GF_LOG_LEVEL: debug
      GF_DATAPROXY_LOGGING: 1
      GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS: alpas-anomalydetector-panel
      GF_RENDERING_SERVER_URL: http://renderer:8081/render
      GF_RENDERING_CALLBACK_URL: http://grafana:3000/
      GF_RENDERING_RENDERER_TOKEN: ${GRAFANA_RENDERER_TOKEN:-anomaly-demo-token}
