apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    uid: demo-prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    jsonData:
      httpMethod: POST
      timeInterval: 5s

  - name: Loki
    type: loki
    uid: demo-loki
    access: proxy
    url: http://loki:3100

  - name: InfluxDB
    type: influxdb
    uid: demo-influxdb
    access: proxy
    url: http://influxdb:8086
    jsonData:
      version: Flux
      organization: anomaly
      defaultBucket: anomaly
    secureJsonData:
      token: anomaly-demo-token

  - name: PostgreSQL
    type: postgres
    uid: demo-postgresql
    access: proxy
    url: postgres:5432
    user: anomaly
    secureJsonData:
      password: anomaly-password
    jsonData:
      database: anomaly
      sslmode: disable
      postgresVersion: 1600

  - name: ClickHouse
    type: grafana-clickhouse-datasource
    uid: demo-clickhouse
    access: proxy
    jsonData:
      host: clickhouse
      port: 8123
      protocol: http
      defaultDatabase: default
      username: default

  - name: Elasticsearch
    type: elasticsearch
    uid: demo-elasticsearch
    access: proxy
    url: http://elasticsearch:9200
    jsonData:
      index: '[grafana-anomaly-]YYYY.MM.DD'
      interval: Daily
      timeField: "@timestamp"
      logMessageField: rule
      logLevelField: severity_label
