services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:9.3.2
    container_name: elastic-benchmark
    environment:
      discovery.type: single-node
      xpack.license.self_generated.type: trial
      xpack.security.enabled: "false"
      xpack.ml.use_auto_machine_memory_percent: "true"
      ES_JAVA_OPTS: -Xms1g -Xmx1g
    ports:
      - "9200:9200"

  kibana:
    profiles: ["ui"]
    image: docker.elastic.co/kibana/kibana:9.3.2
    container_name: kibana-benchmark
    depends_on:
      elasticsearch:
        condition: service_started
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
      TELEMETRY_ENABLED: "false"
    ports:
      - "5601:5601"
